-- AVISO DE SEGURANÇA: políticas RLS provisórias para compatibilidade com a Fase 1.\n-- Antes da produção, migrar autenticação para Supabase Auth e restringir escrita por usuário/admin.\n-- Credenciais, chaves e dados pessoais não devem ser adicionados a este arquivo.\n\n-- Bolão Brasileirão 2026
-- Instalador completo para Supabase/PostgreSQL
-- Execute no Supabase: SQL Editor > New query > Run

begin;

create extension if not exists pgcrypto;

-- Remove apenas objetos deste novo projeto quando o script for repetido.
-- Nenhuma tabela do projeto da Fase 1 é acessada por este arquivo.

create table if not exists public.participants (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  password_hash text,
  is_admin boolean not null default false,
  is_test boolean not null default false,
  created_at timestamptz not null default now(),
  constraint participants_name_not_blank check (length(btrim(name)) >= 2),
  constraint participants_phone_digits check (phone is null or phone ~ '^[0-9]{10,11}$')
);

create unique index if not exists participants_name_lower_uk
  on public.participants (lower(btrim(name)));
create unique index if not exists participants_phone_uk
  on public.participants (phone) where phone is not null;

create table if not exists public.teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  short_name text,
  abbreviation varchar(4),
  crest_url text,
  city text,
  state char(2),
  active boolean not null default true,
  fifa_rank integer,
  fifa_points numeric,
  ranking_reference text,
  updated_at timestamptz not null default now(),
  constraint teams_name_not_blank check (length(btrim(name)) >= 2)
);

create unique index if not exists teams_name_lower_uk
  on public.teams (lower(btrim(name)));

create table if not exists public.games (
  id bigint generated by default as identity primary key,
  season integer not null default 2026,
  round integer not null,
  team1 text not null,
  team2 text not null,
  group_name text generated always as ('Rodada ' || round::text) stored,
  datetime timestamptz not null,
  stadium text,
  status text not null default 'scheduled',
  score1 smallint,
  score2 smallint,
  external_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint games_round_valid check (round between 1 and 38),
  constraint games_distinct_teams check (lower(btrim(team1)) <> lower(btrim(team2))),
  constraint games_score1_valid check (score1 is null or score1 between 0 and 30),
  constraint games_score2_valid check (score2 is null or score2 between 0 and 30),
  constraint games_status_valid check (status in ('scheduled','postponed','suspended','cancelled','live','finished')),
  constraint games_both_scores check ((score1 is null and score2 is null) or (score1 is not null and score2 is not null))
);

create unique index if not exists games_fixture_uk
  on public.games (season, round, lower(btrim(team1)), lower(btrim(team2)));
create unique index if not exists games_external_id_uk
  on public.games (external_id) where external_id is not null;
create index if not exists games_round_datetime_idx
  on public.games (season, round, datetime);
create index if not exists games_status_idx on public.games (status);

create table if not exists public.guesses (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  game_id bigint not null references public.games(id) on delete cascade,
  score1 smallint,
  score2 smallint,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint guesses_score1_valid check (score1 is null or score1 between 0 and 30),
  constraint guesses_score2_valid check (score2 is null or score2 between 0 and 30),
  constraint guesses_both_scores check ((score1 is null and score2 is null) or (score1 is not null and score2 is not null)),
  constraint guesses_participant_game_uk unique (participant_id, game_id)
);

create index if not exists guesses_participant_idx on public.guesses (participant_id);
create index if not exists guesses_game_idx on public.guesses (game_id);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  participant_id uuid not null references public.participants(id) on delete cascade,
  amount numeric(12,2) not null,
  payment_date date not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint payments_amount_positive check (amount > 0),
  constraint payments_one_per_participant unique (participant_id)
);

create table if not exists public.settings (
  id integer primary key default 1,
  competition_name text not null default 'Bolão Brasileirão 2026',
  season integer not null default 2026,
  entry_fee numeric(12,2) not null default 100,
  donation_percent numeric(5,2) not null default 20,
  prize_split integer[] not null default array[50,20,10],
  guess_lock_hours integer not null default 6,
  pix_key text default null,
  updated_at timestamptz not null default now(),
  constraint settings_singleton check (id = 1),
  constraint settings_entry_fee_valid check (entry_fee >= 0),
  constraint settings_donation_valid check (donation_percent between 0 and 100),
  constraint settings_lock_valid check (guess_lock_hours between 0 and 168),
  constraint settings_prize_split_valid check (array_length(prize_split, 1) = 3)
);

insert into public.settings (id)
values (1)
on conflict (id) do nothing;

-- Atualiza automaticamente updated_at.
create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists games_set_updated_at on public.games;
create trigger games_set_updated_at
before update on public.games
for each row execute function public.set_updated_at();

drop trigger if exists guesses_set_updated_at on public.guesses;
create trigger guesses_set_updated_at
before update on public.guesses
for each row execute function public.set_updated_at();

drop trigger if exists teams_set_updated_at on public.teams;
create trigger teams_set_updated_at
before update on public.teams
for each row execute function public.set_updated_at();

drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at
before update on public.payments
for each row execute function public.set_updated_at();

drop trigger if exists settings_set_updated_at on public.settings;
create trigger settings_set_updated_at
before update on public.settings
for each row execute function public.set_updated_at();

-- Impede palpites após a janela de bloqueio definida em settings.
create or replace function public.validate_guess_deadline()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  kickoff timestamptz;
  game_status text;
  lock_hours integer;
begin
  select g.datetime, g.status into kickoff, game_status
  from public.games g where g.id = new.game_id;

  select s.guess_lock_hours into lock_hours
  from public.settings s where s.id = 1;

  if kickoff is null then
    raise exception 'Jogo não encontrado.';
  end if;

  if game_status <> 'scheduled' then
    raise exception 'Palpites não podem ser alterados para jogo com status %.', game_status;
  end if;

  if now() >= kickoff - make_interval(hours => coalesce(lock_hours, 6)) then
    raise exception 'Palpites encerrados para esta partida.';
  end if;

  return new;
end;
$$;

drop trigger if exists guesses_validate_deadline on public.guesses;
create trigger guesses_validate_deadline
before insert or update of score1, score2, game_id on public.guesses
for each row execute function public.validate_guess_deadline();

-- Ranking calculado com as regras atuais: 5 pontos exato, 3 pelo resultado.
create or replace view public.ranking as
select
  p.id as participant_id,
  p.name,
  coalesce(sum(
    case
      when g.score1 is null or g.score2 is null or b.score1 is null or b.score2 is null then 0
      when b.score1 = g.score1 and b.score2 = g.score2 then 5
      when sign(b.score1 - b.score2) = sign(g.score1 - g.score2) then 3
      else 0
    end
  ), 0)::integer as points
from public.participants p
left join public.guesses b on b.participant_id = p.id
left join public.games g on g.id = b.game_id
where not p.is_test
group by p.id, p.name;

-- Segurança compatível com o código copiado da Fase 1.
alter table public.participants enable row level security;
alter table public.teams enable row level security;
alter table public.games enable row level security;
alter table public.guesses enable row level security;
alter table public.payments enable row level security;
alter table public.settings enable row level security;

drop policy if exists participants_read on public.participants;
create policy participants_read on public.participants for select to anon, authenticated using (true);
drop policy if exists participants_register on public.participants;
create policy participants_register on public.participants for insert to anon, authenticated with check (is_admin = false);
drop policy if exists participants_compat_update on public.participants;
create policy participants_compat_update on public.participants for update to anon, authenticated using (true) with check (true);
drop policy if exists participants_compat_delete on public.participants;
create policy participants_compat_delete on public.participants for delete to anon, authenticated using (true);

drop policy if exists teams_read on public.teams;
create policy teams_read on public.teams for select to anon, authenticated using (true);

drop policy if exists games_read on public.games;
create policy games_read on public.games for select to anon, authenticated using (true);
drop policy if exists games_compat_update on public.games;
create policy games_compat_update on public.games for update to anon, authenticated using (true) with check (true);

drop policy if exists guesses_read on public.guesses;
create policy guesses_read on public.guesses for select to anon, authenticated using (true);
drop policy if exists guesses_insert on public.guesses;
create policy guesses_insert on public.guesses for insert to anon, authenticated with check (true);
drop policy if exists guesses_update on public.guesses;
create policy guesses_update on public.guesses for update to anon, authenticated using (true) with check (true);

drop policy if exists payments_read on public.payments;
create policy payments_read on public.payments for select to anon, authenticated using (true);

drop policy if exists settings_read on public.settings;
create policy settings_read on public.settings for select to anon, authenticated using (true);

grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on public.participants to anon, authenticated;
grant select on public.teams to anon, authenticated;
grant select, update on public.games to anon, authenticated;
grant select, insert, update on public.guesses to anon, authenticated;
grant select on public.payments to anon, authenticated;
grant select on public.settings to anon, authenticated;
grant select on public.ranking to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

commit;

-- PASSO POSTERIOR: após cadastrar Nelson pelo aplicativo, execute:
-- update public.participants
-- set is_admin = true
-- where lower(btrim(name)) = lower('Nelson');

-- CONSULTAS DE CONFERÊNCIA:
-- select * from public.settings;
-- select table_name from information_schema.tables where table_schema = 'public' order by table_name;
-- select * from public.ranking order by points desc, name;
